### ISSUE TITLE
Install via Composer request.

### ISSUE THREAD

**Issue by dexcell** [thenbrent/paypal-digital-goods#23]
Hi, it would be nice if we can install this via composer.
Just like modern php package.

Thank you

**Comment by thenbrent** [comment]
@dexcell as I do mostly WordPress product development, I'm not familiar with setting up composer packages. If you want to set it up, I'm happy to merge a pull request with any changes needed in the library.

**Comment by zephinzer** [comment]
@thenbrent trying out Composer packaging for this library, not entirely sure if this will work because it's my first time but I think it's worth a shot since I want to include this library using Composer in my own application.

**Comment by dakshhmehta** [comment]
I just added a folder to autoload array and it worked fine..

**Comment by thenbrent** [comment]
@dakshhmehta thanks for the confirmation. I've just merged #27 :+1:
