### ISSUE TITLE
Paypal Subscription Sandbox Error

### ISSUE THREAD

**Issue by xdkoc** [thenbrent/paypal-digital-goods#24]
Test with your example pages, purchase method works well.
Subscription Method interrupts after Login on Paypal (Sandbox) -> Cancel Payment.

looks like the problem is only for german subscribers
Can you confirm?

**Comment by thenbrent** [comment]
@xdkoc I have heard about issues relating to Subscriptions and german subscribers, unfortunately as I don't have a german sandbox account, I can't test it at all.

If you can provide example credentials for a German sandbox that might help me diagnose it.
