### ISSUE TITLE
Pupup after click on pay botton

### ISSUE THREAD

**Issue by stojankukrika** [thenbrent/paypal-digital-goods#25]
First, I would like to thank you in this great library! Its awesome!
And now I have one question. How to open pay window on same window or on other tab or something.. because he open two more popup-s, look the picture. Is there any chance to fix it on something or must be something like that to secure payment?

BR,
Stojan
![testpaypall](https://cloud.githubusercontent.com/assets/10199584/6060614/5da73d4a-ad3f-11e4-8b81-6229eb4f5e58.png)

**Comment by stojankukrika** [comment]
Oh yea....I have one problem.. when I integrate in on my site. When I finished pay or cancel, he open only cancel or success page in popup, do not close popup and this is confusing a little bit. because, I must hard code link to back to site. Site is make in codeigniter framework.

**Comment by bartreijmer** [comment]
You can only 'reactivate' by starting a new subscription if you cancel the subscription.

**Comment by thenbrent** [comment]
> You can only 'reactivate' by starting a new subscription if you cancel the subscription.

Yes, that's correct. Only suspended subscriptions can be reactivated.

> How to open pay window on same window or on other tab or something

That's closer to the default PayPal Express Checkout behaviour. If you want that behaviour, you should try those payment options.

> Is there any chance to fix it on something or must be something like that to secure payment?

I'm pretty sure PayPal open it in a new popup to show the customer that they are actually entering their credentials on the PayPal site. If the customer was already logged in, the first popup would show the payment details (for non-subscription purchases).
