### ISSUE TITLE
Subscription postback

### ISSUE THREAD

**Issue by alexa026** [thenbrent/paypal-digital-goods#28]
Hello,
cheers for fantastic script. I have a question regarding subscription postback, is there a way to make a a postback every month/week whenever recurring payment is done? I would like to have some kind of "notification" when user cancels subscription.

**Comment by thenbrent** [comment]
@alexa026 yes, PayPal will send a postback via their IPN to the URL you specify with `PayPal_Digital_Goods_Configuration::notify_url()`. You can learn more about IPN here: https://developer.paypal.com/docs/classic/products/instant-payment-notification/
