### ISSUE TITLE
Handling errors (specifically Error 10486)

### ISSUE THREAD

**Issue by iadj** [thenbrent/paypal-digital-goods#32]
The most common error with Paypal Express Checkout is people not having a valid funding source (code 10486).
I'm confused on how to integrate this properly. Paypal currently simply says 'Something went wrong, please try again later', but there's a way to redirect the user to their funding source page while being able to complete the payment after selecting a working funding source: https://developer.paypal.com/docs/classic/express-checkout/ht_ec_fundingfailure10486

I'd love to see this error handled correctly, and possibly a way to handle other errors too.

**Comment by thenbrent** [comment]
> I'd love to see this error handled correctly, and possibly a way to handle other errors too.

So would I but I won't be implementing it. Patches welcome if you write the code to handle it. :)
