### ISSUE TITLE
clicking on close button in minibrowser of paypal adaptive embedded flow,unable to redirect to 

### ISSUE THREAD

**Issue by sagarchinta** [thenbrent/paypal-digital-goods#38]
I have embedded flow for paypal adaptive payment with code 
        <html>
    <head>
    <script src="https://www.paypalobjects.com/js/external/dg.js"    type="text/javascript"></script>
    </head>

    <body>
    <form    action="https://www.sandbox.paypal.com/webapps/adaptivepayment/flow/pay" target="PPDGFrame" class="standard">
    <label for="buy">Buy Now:</label>
    <input type="image" id="submitBtn" value="Pay with PayPal" src="https://www.paypalobjects.com/en_US/i/btn/btn_paynowCC_LG.gif">
    <input id="type" type="hidden" name="expType" value="light">
    <input id="paykey" type="hidden" name="paykey" value="<?php echo $PayKey ?>">
    </form>

    <script type="text/javascript" charset="utf-8">
    var embeddedPPFlow = new PAYPAL.apps.DGFlow({trigger: 'submitBtn'});
    </script>
    </body>
    </html>
From the page http://localhost/ecommerce/subscription/1/register     -[before_pay_url] I am going to mini-window.

In the Pay() request- I set the return_url as http://localhost/ecommerce/paypal/adaptive_payments/payment_details    -  [after_pay_url]

After the completion of payment from mini-window there is the close button.Now on click of that close button I want to goto url [after_pay_url]

But what is happening is that on click of close button the contents of [after_pay_url] are displayed on same page [before_pay_url]

So the question is how could I get redirected to page on click on close button of embedded paypal mini-browser

**Comment by thenbrent** [comment]
Hi @sagarchinta try asking this at stackoverflow.com or another site devoted to developer questions. 

GitHub and these Issues are for reporting bugs or issues with the PayPal Digital Goods for Express Checkout library. They're not for help with other PayPal issues, like this one which seems to be related to PayPal Adaptive Payments, or custom integrations. I don't work for PayPal or provide technical support for their products. :smile:
