### ISSUE TITLE
Enabling the live mode results (SetExpressCheckout has Failed)

### ISSUE THREAD

**Issue by mahmoudrabie** [thenbrent/paypal-digital-goods#41]
Hi Brent,

The plugin works perfectly in Paypal sandbox mode.

However, enabling live mode result the following error:
Calling PayPal with action SetExpressCheckout has Failed: You are not signed up to accept payment for digitally delivered goods.

I would appreciate any help you provide.

Regards
Mahmoud

**Comment by thenbrent** [comment]
Hi @mahmoudrabie,

Based on that message, it sounds like you are not signed up to accept payment for digitally delivered goods. PayPal needs to enabled Digital Goods support on your account manually for it to be available.

Unfortunately, PayPal are unlikely to enable it on new accounts as, based on the [developer docs](https://developer.paypal.com/docs/classic/express-checkout/digital-goods/IntroducingExpressCheckoutDG/), they have deprecated Digital Goods:

> [The PayPal Digital Goods] integration method is Deprecated as of January 1, 2017

Screenshot of that page: https://cl.ly/3t0L3O220W1K

**Comment by mahmoudrabie** [comment]
Brent,

Thanks a lot for your reply.

Is there any solution or even workaround because I bought Wordpress theme (Properta) that relies on your code ?

Regards
Mahmoud

**Comment by thenbrent** [comment]
@mahmoudrabie I think PayPal moved many of the benefits of Digital Goods (like in-context checkout) into their standard Express Checkout solution, so hopefully you can find an Express Checkout option which supports in-context payments.

I would start by looking at WooCommerce and Express Checkout plugins for it. It's significantly better to use WC for most cases these days than it is to try to integrate directly with PayPal like we used to have to do. Good luck!
