### ISSUE TITLE
Outdated?

### ISSUE THREAD

**Issue by janstieler** [thenbrent/paypal-digital-goods#42]
Hi,
is this Class actual maintained or is it outdated?
Cheers

**Comment by thenbrent** [comment]
Hi @janstieler, the class still works, though it's not actively maintained (if there were major issued, I'd look at them, but that's unlikely given this has been in use in products for many years now).

The PayPal Digital Goods product has been discontinued, and no new accounts will be approved by PayPal for Digital Goods, so it doesn't make a lot of sense for it to be used for new integrations. Better to start with a newer API now. :)
